#global
tag: 1.0.21

# Database settings
mysql:
  image: mysql:8.0
  rootPassword: password
  externalPort: 63306

# Worldserver settings
worldserver:
  image: biltisberger/ac-wotlk-worldserver
  user: acore
  worldPort: 8085
  soapPort: 7878

# Authserver settings
authserver:
  image: biltisberger/ac-wotlk-authserver
  port: 3724

# Eluna TypeScript settings
elunaTs:
  image: biltisberger/eluna-ts:master

acDbImport:
  image: biltisberger/ac-wotlk-db-import
  environment:
    AC_DISABLE_INTERACTIVE: "1"
    AC_DATA_DIR: "/azerothcore/env/dist/data"
    AC_LOGS_DIR: "/azerothcore/env/dist/logs"
    AC_LOGIN_DATABASE_INFO: "ac-database;3306;root;password;acore_auth"
    AC_WORLD_DATABASE_INFO: "ac-database;3306;root;password;acore_world"
    AC_CHARACTER_DATABASE_INFO: "ac-database;3306;root;password;acore_characters"
    AC_CLOSE_IDLE_CONNECTIONS: "0"

acClientData:
  image: biltisberger/ac-wotlk-client-data
  volume:
    name: ac-client-data
    mountPath: /azerothcore/env/dist/data

# Volumes
persistence:
  enabled: true
  dataVolumeSize: 20Gi
  databaseVolumeSize: 5Gi
