# Database settings
mysql:
  image: mysql:8.0
  rootPassword: password
  externalPort: 63306

# Worldserver settings
worldserver:
  image: acore/ac-wotlk-worldserver:12.0.0-dev.1
  user: acore
  worldPort: 8085
  soapPort: 7878

# Authserver settings
authserver:
  image: acore/ac-wotlk-authserver:12.0.0-dev.1
  port: 3724

# PhpMyAdmin
phpmyadmin:
  image: phpmyadmin
  port: 8080

# Eluna TypeScript settings
elunaTs:
  image: acore/eluna-ts:master

acDbImport:
  image: acore/ac-wotlk-db-import:12.0.0-dev.1
  environment:
    AC_DISABLE_INTERACTIVE: "1"
    AC_DATA_DIR: "/azerothcore/env/dist/data"
    AC_LOGS_DIR: "/azerothcore/env/dist/logs"
    AC_LOGIN_DATABASE_INFO: "ac-database;3306;root;password;acore_auth"
    AC_WORLD_DATABASE_INFO: "ac-database;3306;root;password;acore_world"
    AC_CHARACTER_DATABASE_INFO: "ac-database;3306;root;password;acore_characters"
    AC_CLOSE_IDLE_CONNECTIONS: "0"

acClientData:
  image: acore/ac-wotlk-client-data:12.0.0-dev.1
  volume:
    name: ac-client-data
    mountPath: /azerothcore/env/dist/data

# Volumes
persistence:
  enabled: true
  dataVolumeSize: 20Gi
  databaseVolumeSize: 5Gi
