apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ac-client-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.acClientData.volume.size }}
