apiVersion: batch/v1
kind: Job
metadata:
  name: ac-client-data
spec:
  backoffLimit: 10
  selector:
    matchLabels:
      app: ac-client-data
  template:
    metadata:
      labels:
        app: ac-client-data
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ac-client-data
          image: "{{ .Values.acClientData.image }}"
          volumeMounts:
            - name: ac-data
              mountPath: "{{ .Values.acClientData.volume.mountPath }}"
      volumes:
        - name: ac-data
          persistentVolumeClaim:
            claimName: ac-data
