apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ac-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.dataVolumeSize }}
  storageClassName: nfs
