apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-azeroth-core
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.dataVolumeSize }}
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: nfs-server-azeroth-core
