apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-azeroth-core
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.persistence.dataVolumeSize }}
  mountOptions:
  - nolock
  nfs:
    path: /exports
    server: nfs-service
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
