apiVersion: v1
kind: PersistentVolume
metadata:
  name: ac-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: {{ .Values.persistence.dataVolumeSize }}
  mountOptions:
  - nolock
  nfs:
    path: /exports
    server: nfs-service.{{ .Release.Namespace }}.svc.cluster.local
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
