apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worldserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.databaseVolumeSize }}
