apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-worldserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac-worldserver
  template:
    metadata:
      labels:
        app: ac-worldserver
    spec:
      containers:
        - name: worldserver
          env:
            - name: AC_LOGIN_DATABASE_INFO
              value: ac-database;3306;root;root;acore_auth
            - name: AC_CHARACTER_DATABASE_INFO
              value: ac-database;3306;root;root;acore_characters
            - name: AC_WORLD_DATABASE_INFO
              value: ac-database;3306;root;root;acore_world
          image: "{{ .Values.authserver.image }}"
          tty: true
          stdin: true
          image: "{{ .Values.worldserver.image }}"
          ports:
            - containerPort: {{ .Values.worldserver.worldPort }}
            - containerPort: {{ .Values.worldserver.soapPort }}
          env:
            - name: AC_USER
              value: "{{ .Values.worldserver.user }}"
          volumeMounts:
            - name: worldserver-data
              mountPath: /path/to/worldserver/data
      volumes:
        - name: worldserver-data
          persistentVolumeClaim:
            claimName: worldserver-pvc
            