apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-worldserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac-worldserver
  template:
    metadata:
      labels:
        app: ac-worldserver
    spec:
      containers:
        - name: worldserver
          image: "{{ .Values.worldserver.image }}:{{ .Values.tag }}"
          tty: true
          stdin: true
          ports:
            - containerPort: {{ .Values.worldserver.worldPort }}
            - containerPort: {{ .Values.worldserver.soapPort }}
          env:
            - name: AC_USER
              value: "{{ .Values.worldserver.user }}"
            - name: AC_LOGS_DIR
              value: /azerothcore/env/dist/logs
            - name: AC_DATA_DIR
              value: /azerothcore/env/dist/data
            - name: AC_LOGIN_DATABASE_INFO
              value: ac-database;3306;root;password;acore_auth
            - name: AC_CHARACTER_DATABASE_INFO
              value: ac-database;3306;root;password;acore_characters
            - name: AC_WORLD_DATABASE_INFO
              value: ac-database;3306;root;password;acore_world
          volumeMounts:
            - name: ac-data
              mountPath: "{{ .Values.acClientData.volume.mountPath }}"
      volumes:
        - name: ac-data
          persistentVolumeClaim:
            claimName: ac-data
            